Repository nanoframework/System.Device.Gpio, pull requests merged in 2020-10, with the labels that each got.

#1 Adding managed System.Device.Gpio
  README.md
  System.Device.Gpio/GpioController.cs
  System.Device.Gpio/PinChangeEventHandler.cs
  System.Device.Gpio/PinEventTypes.cs
  System.Device.Gpio/PinMode.cs
  System.Device.Gpio/PinNumberingScheme.cs
  System.Device.Gpio/PinValue.cs
  System.Device.Gpio/PinValueChangedEventArgs.cs
  System.Device.Gpio/PinValuePair.cs
  System.Device.Gpio/README.txt
  System.Device.Gpio/System.Device.Gpio.nfproj
  System.Device.Gpio/WaitEventResult.cs
  System.Device.Gpio/WaitForEventResult.cs
  System.Device.Gpio/key.snk
  System.Device.Gpio/packages.config
  nanoFramework.System.Device.Gpio.DELIVERABLES.nuspec
  nanoFramework.System.Device.Gpio.nuspec
  nanoFramework.System.Device.Gpio.sln
Labels: Area: Config-and-Build, Type: dependencies, Type: enhancement

#2 Move to fully native implementation
  .editorconfig
  System.Device.Gpio/GpioController.cs
  System.Device.Gpio/GpioPin.cs
  System.Device.Gpio/GpioPinEvent.cs
  System.Device.Gpio/GpioPinEventListener.cs
  System.Device.Gpio/PinValueChangedEventArgs.cs
  System.Device.Gpio/Properties/AssemblyInfo.cs
  System.Device.Gpio/System.Device.Gpio.nfproj
  System.Device.Gpio/packages.config
  Windows.Devices.Gpio/Extensions/Gpio​PinExtensions.cs
  Windows.Devices.Gpio/GpioChangePolarity.cs
  Windows.Devices.Gpio/GpioController.cs
  Windows.Devices.Gpio/GpioOpenStatus.cs
  Windows.Devices.Gpio/GpioPinDriveMode.cs
  Windows.Devices.Gpio/GpioPinEdge.cs
  Windows.Devices.Gpio/GpioPinValue.cs
  Windows.Devices.Gpio/GpioPinValueChangedEventArgs.cs
  Windows.Devices.Gpio/GpioSharingMode.cs
  Windows.Devices.Gpio/Gpio​Change​Count.cs
  Windows.Devices.Gpio/Gpio​Change​Counter.cs
  Windows.Devices.Gpio/Gpio​Change​Reader.cs
  Windows.Devices.Gpio/Gpio​Change​Record.cs
  Windows.Devices.Gpio/IGpioController.cs
  Windows.Devices.Gpio/IGpioPin.cs
  Windows.Devices.Gpio/Provider/IGpioControllerProvider.cs
  Windows.Devices.Gpio/Provider/IGpioPinProvider.cs
  Windows.Devices.Gpio/Provider/IGpioProvider.cs
  Windows.Devices.Gpio/Provider/ProviderGpioPinDriveMode.cs
  Windows.Devices.Gpio/Provider/ProviderGpioPinEdge.cs
  Windows.Devices.Gpio/Provider/ProviderGpioPinValue.cs
  Windows.Devices.Gpio/Provider/ProviderGpioSharingMode.cs
  Windows.Devices.Gpio/README.txt
  Windows.Devices.Gpio/Windows.Devices.Gpio.nfproj
  Windows.Devices.Gpio/key.snk
  Windows.Devices.Gpio/packages.config
  nanoFramework.System.Device.Gpio.nuspec
  nanoFramework.System.Device.Gpio.sln
  nanoFramework.Windows.Devices.Gpio.DELIVERABLES.nuspec
  nanoFramework.Windows.Devices.Gpio.nuspec
  nanoFramework.Windows.Devices.Gpio.sln
Labels: Type: enhancement, hacktoberfest-accepted

#3 Improve Controller to have OpenGpio methods returning a GpioPin
  System.Device.Gpio/GpioController.cs
  System.Device.Gpio/Properties/AssemblyInfo.cs
  System.Device.Gpio/System.Device.Gpio.nfproj
Labels: Type: enhancement, hacktoberfest-accepted

#6 Rename DriveMode with PinMode.
  System.Device.Gpio/GpioController.cs
  System.Device.Gpio/GpioPin.cs
  System.Device.Gpio/Properties/AssemblyInfo.cs
Labels: Breaking-Change

#7 Improvements in GpioPin
  System.Device.Gpio/GpioController.cs
  System.Device.Gpio/GpioPin.cs
  System.Device.Gpio/Properties/AssemblyInfo.cs
Labels: Type: bug, Type: enhancement

#8 Remove _lastOutputValue field from GpioPin
  System.Device.Gpio/GpioPin.cs
  System.Device.Gpio/Properties/AssemblyInfo.cs
Labels: Type: enhancement

#9 Improve GpioControllerValueChanged
  System.Device.Gpio/GpioController.cs
Labels: Type: enhancement
